### ISSUE TITLE
readtle() takes exactly 3 arguments

### ISSUE THREAD

**Issue by bdefore** [trehn/termtrack#2]
I'm unable to run the library. Are any options required?

```
→ termtrack hubble
Traceback (most recent call last):
  File "/usr/local/bin/termtrack", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/termtrack/cli.py", line 395, in main
    curses.wrapper(render, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/termtrack/utils/curses.py", line 429, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/termtrack/cli.py", line 144, in render
    tle_file=tle,
  File "/usr/local/lib/python3.5/site-packages/termtrack/satellite.py", line 89, in __init__
    self._satellite = ephem.readtle(*tle)
TypeError: readtle() takes exactly 3 arguments (1 given)
```

**Comment by trehn** [comment]
Not your fault, the underlying issue is that TLE data is no longer returned from

http://www.celestrak.com/cgi-bin/TLE.pl?CATNR=20580

Maybe it's just a temporary issue. In the meantime you can download the data manually from http://www.celestrak.com/NORAD/elements/master.asp, save it to a file and load it with `--tle`.

**Comment by trehn** [comment]
https://twitter.com/trehn/status/753642458484015104

**Comment by trehn** [comment]
Has been fixed at Celestrak. I'll try to add a more useful error message when I get around to it.

Enjoy!

**Comment by bdefore** [comment]
Confirmed working now. Thanks!
