### ISSUE TITLE
termtrack crashes on windows 10

### ISSUE THREAD

**Issue by ynx0** [trehn/termtrack#5]
I just installed termtrack using `pip3 install termtrack` and tried running the commands:
* `termtrack`
* `termtrack -figmntxo 1 less`

Both commands crash and output the same python stacktrace.
<details>
<summary>
Stacktrace
</summary>

```Traceback (most recent call last):
  File "c:\users\lux\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lux\AppData\Local\Programs\Python\Python36\Scripts\termtrack.exe\__main__.py", line 9, in <module>
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\termtrack\cli.py", line 403, in main
    curses.wrapper(render, **kwargs)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\termtrack\utils\curses.py", line 429, in wrapper
    func(*args, **kwargs)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\termtrack\cli.py", line 105, in render
    curses_lock, input_queue, quit_event = setup(stdscr)
  File "c:\users\lux\appdata\local\programs\python\python36\lib\site-packages\termtrack\utils\curses.py", line 460, in setup
    curses.init_pair(i + 1, i, -1)
_curses.error: init_pair() returned ERR
```

</details>

Computer Details:
* OS: Windows 10
* Terminal Program: Hyper
* Python: 3.6.5

**Comment by Clepalitto** [comment]
I also tried running the program on Windows 10 after installing it with pip3, but the following error appeared :

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\termtrack.exe\__main__.py", line 4, in <module>
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python39\lib\site-packages\termtrack\cli.py", line 1, in <module>
    import curses
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

And I can't figure out how to fix it.

**Comment by AydinAlptug** [comment]
Have you tried this? @Clepalitto 

`pip install windows-curses`
