### ISSUE TITLE
TypeError: readtle() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by Salomanuel** [trehn/termtrack#8]
the app crashes and I don't get which other arguments should I give it
(it used to work fine one year ago)

```
termtrack -figmntxo 1 iss                                                                                                              
Traceback (most recent call last):
  File "/Users/manuel/.pyenv/versions/3.9.5/bin/termtrack", line 8, in <module>
    sys.exit(main())
  File "/Users/manuel/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manuel/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/manuel/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manuel/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/manuel/.pyenv/versions/3.9.5/lib/python3.9/site-packages/termtrack/cli.py", line 402, in main
    curses.wrapper(render, **kwargs)
  File "/Users/manuel/.pyenv/versions/3.9.5/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/manuel/.pyenv/versions/3.9.5/lib/python3.9/site-packages/termtrack/utils/curses.py", line 429, in wrapper
    func(*args, **kwargs)
  File "/Users/manuel/.pyenv/versions/3.9.5/lib/python3.9/site-packages/termtrack/cli.py", line 141, in render
    satellite_obj = EarthSatellite(
  File "/Users/manuel/.pyenv/versions/3.9.5/lib/python3.9/site-packages/termtrack/satellite.py", line 87, in __init__
    self._satellite = ephem.readtle(*tle)
TypeError: readtle() takes exactly 3 arguments (1 given)
```

my machine:
```
Last login: Tue Jun  7 12:19:18 on console
                    'c.          manuel@Manuels-MacBook-Pro-M1.local
                 ,xNMM.          -----------------------------------
               .OMMMMo           OS: macOS 12.4 21F79 arm64
               OMMM0,            Host: MacBookPro17,1
     .;loddo:' loolloddol;.      Kernel: 21.5.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 204 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Rectangle
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: MesloLGS-NF-Regular 16
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1949MiB / 16384MiB
       .cooc,.    .,coo:.

```

**Comment by trehn** [comment]
Update is out, `pip install -U termtrack`

**Comment by Salomanuel** [comment]
thanks a lot, beautiful job :)
