### ISSUE TITLE
"TypeError: readtle() takes exactly 3 arguments (1 given)" when trying to track JWST

### ISSUE THREAD

**Issue by Br3nnabee** [trehn/termtrack#9]
Hi, I've been using termtrack for a while with no issues, however I've noticed that when trying to track the James Webb Space Telescope (no other satellites I've tried have had this issue), I get this output:

```termtrack -figmntxo 1 50463                                                                                                                                                  ✔ ╱ 3s  ╱ !1/5  
Traceback (most recent call last):
  File "/Users/user/homebrew/bin/termtrack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/termtrack/cli.py", line 402, in main
    curses.wrapper(render, **kwargs)
  File "/Users/user/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/termtrack/utils/curses.py", line 429, in wrapper
    func(*args, **kwargs)
  File "/Users/user/homebrew/lib/python3.11/site-packages/termtrack/cli.py", line 141, in render
    satellite_obj = EarthSatellite(
                    ^^^^^^^^^^^^^^^
  File "/Users/user/homebrew/lib/python3.11/site-packages/termtrack/satellite.py", line 87, in __init__
    self._satellite = ephem.readtle(*tle)
                      ^^^^^^^^^^^^^^^^^^^
TypeError: readtle() takes exactly 3 arguments (1 given)
```
Looking at prior issues, it seems that this may be a database issue, but is there anything I can do to remedy this?

**Comment by thkruz** [comment]
JWST is not orbiting the earth. Two line element sets are only valid if Earth is the central body. I like to use [n2yo](https://www.n2yo.com/satellite/?s=50463) as a quick sanity check that a two line element set is still being published, but you can cross reference [celestrak.org](celestrak.org), [space-track.org](space-track.org), or my site [keeptrack.space](keeptrack.space) to make sure there is actually a TLE to be found.

It would be helpful if termtrack output a more explicit error about what was being input or if it did a validity check and warned you if no TLE was found.

Try rerunning with satellite 00002 and see if you get the same error. Sputnik is also no longer orbiting Earth😄

**Comment by Br3nnabee** [comment]
Sorry, I was under the impression they could still depict relative position even if it was at a lagrange point. My apologies!
